# ios/project.yml
name: monGARS

options:
  bundleIdPrefix: com.offllm
  deploymentTarget:
    iOS: "18.0"
  # Keep postGenCommand, but make it deterministic and CI-friendly.
  # CocoaPods must run after XcodeGen so the workspace exists.
  postGenCommand: |
    set -euo pipefail
    pod install --project-directory=. --verbose

packages:
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    exactVersion: 0.25.6
  mlx-swift-examples:
    url: https://github.com/ml-explore/mlx-swift-examples
    exactVersion: 2.25.6

settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: c++20
    CLANG_CXX_LIBRARY: libc++
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"
          - "MLXCompat.swift"
        # IMPORTANT: do NOT exclude Resources/** if you also declare resources below.
        # Excluding it can confuse incremental builds and bundle scripts.

    resources:
      # Keep these optional so CI doesn't fail if empty/missing.
      - path: MyOfflineLLMApp/Resources
        type: folder
        optional: true
      - path: MyOfflineLLMApp/Models
        type: folder
        optional: true

    dependencies:
      # iOS system frameworks required by your native modules
      - sdk: Contacts.framework
      - sdk: CoreLocation.framework
      - sdk: CoreMotion.framework
      - sdk: EventKit.framework
      - sdk: MapKit.framework
      - sdk: MediaPlayer.framework
      - sdk: MessageUI.framework
      - sdk: Photos.framework

      # MLX + LLM
      - package: mlx-swift-examples
        product: MLXLLM
      - package: mlx-swift-examples
        product: MLXLMCommon
      - package: mlx-swift
        product: MLX
      - package: mlx-swift
        product: MLXNN
      - package: mlx-swift
        product: MLXLinalg
      - package: mlx-swift
        product: MLXFFT

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.mongars
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: MyOfflineLLMApp/Bridging/monGARS-Bridging-Header.h

        CLANG_CXX_LIBRARY: libc++
        OTHER_MTLFLAGS:
          - "$(inherited)"
          - "-std=metal-cpp17"

        # Default: unsigned. We only enable signing in Release via configurations below.
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

      configurations:
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

          # Signing (manual) for App Store / TestFlight archives
          CODE_SIGNING_ALLOWED: YES
          CODE_SIGNING_REQUIRED: YES
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: 52T7P32J34

          # Prefer a concrete identity name.
          # If you want absolute determinism, set this to the full identity string:
          #   "Apple Distribution: <Your Legal Name> (<TEAMID>)"
          CODE_SIGN_IDENTITY: "Apple Distribution"

          # IMPORTANT: Prefer UUID in CI (more reliable than name).
          # Your workflow already exports PROFILE_UUID; you can pass it to xcodebuild
          # as PROVISIONING_PROFILE. Leaving SPECIFIER here is fine for local builds.
          PROVISIONING_PROFILE_SPECIFIER: "monGARS"

        Debug:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGN_IDENTITY: ""
          DEVELOPMENT_TEAM: ""

    scripts:
      - name: Bundle React Native code and images
        shell: /bin/bash
        script: |
          set -euo pipefail

          # Xcode 15/16: ensure node is resolvable (RN script uses NODE_BINARY).
          export NODE_BINARY="${NODE_BINARY:-$(command -v node || true)}"
          if [[ -z "${NODE_BINARY}" ]]; then
            echo "::error::node not found on PATH"
            exit 1
          fi

          export RCT_METRO_PORT="${RCT_METRO_PORT:-8081}"

          # For archives we want deterministic bundling.
          if [[ "${CONFIGURATION}" == "Release" ]]; then
            export EXTRA_PACKAGER_ARGS="${EXTRA_PACKAGER_ARGS:---minify}"
          fi

          # RN bundling script
          "${SRCROOT}/../node_modules/react-native/scripts/react-native-xcode.sh"
        inputFiles:
          - "${SRCROOT}/../index.js"
          - "${SRCROOT}/../package.json"
          - "${SRCROOT}/../app.json"
          - "${SRCROOT}/../babel.config.js"
          - "${SRCROOT}/../metro.config.js"
          - "${SRCROOT}/../node_modules/react-native/scripts
