name: monGARS

options:
  bundleIdPrefix: com.offllm
  deploymentTarget:
    iOS: "18.0"
  postGenCommand: pod install --project-directory=.

packages:
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    exactVersion: 0.25.6
  mlx-swift-examples:
    url: https://github.com/ml-explore/mlx-swift-examples
    exactVersion: 2.25.6

settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: c++20
    CLANG_CXX_LIBRARY: libc++

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"
          - "MLXCompat.swift"
          - "Resources/**"

    resources:
      - path: MyOfflineLLMApp/Resources
        type: folder
        optional: true
      - path: MyOfflineLLMApp/Models
        type: folder
        optional: true

    dependencies:
      - sdk: Contacts.framework
      - sdk: CoreLocation.framework
      - sdk: CoreMotion.framework
      - sdk: EventKit.framework
      - sdk: MapKit.framework
      - sdk: MediaPlayer.framework
      - sdk: MessageUI.framework
      - sdk: Photos.framework

      - package: mlx-swift-examples
        product: MLXLLM
      - package: mlx-swift
        product: MLX
      - package: mlx-swift
        product: MLXNN
      - package: mlx-swift
        product: MLXLinalg
      - package: mlx-swift
        product: MLXFFT
      - package: mlx-swift-examples
        product: MLXLMCommon

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.mongars
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SWIFT_OBJC_BRIDGING_HEADER: MyOfflineLLMApp/Bridging/monGARS-Bridging-Header.h

        CLANG_CXX_LIBRARY: libc++
        OTHER_MTLFLAGS:
          - "$(inherited)"
          - "-std=metal-cpp17"
        ENABLE_USER_SCRIPT_SANDBOXING: NO

      configurations:
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          DEVELOPMENT_TEAM: 52T7P32J34
          CODE_SIGN_STYLE: Manual
          # IMPORTANT: set this to your real profile name if you want local Release signing.
          # In CI we pass PROVISIONING_PROFILE_SPECIFIER dynamically anyway.
          PROVISIONING_PROFILE_SPECIFIER: offLLM
          CODE_SIGN_IDENTITY: "Apple Distribution"

        Debug:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGN_IDENTITY: ""
          DEVELOPMENT_TEAM: ""

    scripts:
      - name: Bundle React Native code and images
        shell: /bin/bash
        script: |
          set -euo pipefail
          export NODE_BINARY="${NODE_BINARY:-node}"
          export RCT_METRO_PORT="${RCT_METRO_PORT:-8081}"
          if [[ "${CONFIGURATION}" == "Release" ]]; then
            export EXTRA_PACKAGER_ARGS="${EXTRA_PACKAGER_ARGS:---minify}"
          fi
          "${SRCROOT}/../node_modules/react-native/scripts/react-native-xcode.sh"
        inputFiles:
          - "${SRCROOT}/../index.js"
          - "${SRCROOT}/../package.json"
          - "${SRCROOT}/../app.json"
          - "${SRCROOT}/../babel.config.js"
          - "${SRCROOT}/../metro.config.js"
          - "${SRCROOT}/../node_modules/react-native/scripts/react-native-xcode.sh"
        outputFiles:
          - "${DERIVED_FILE_DIR}/bundle-react-native.stamp"
        runOnlyForDeploymentPostprocessing: false

schemes:
  monGARS:
    shared: true
    build:
      targets:
        monGARS: all
      preActions:
        - name: Purge legacy RCTDeprecation caches
          settingsTarget: monGARS
          script: |
            bash "${PROJECT_DIR}/scripts/purge-rctdeprecation-caches.sh"
        - name: Patch MLX metal headers for C++17 warnings
          settingsTarget: monGARS
          script: |
            bash "${PROJECT_DIR}/scripts/patch-mlx-metal-cxx17.sh"
    run:
      config: Debug
    test:
      config: Debug
      targets: []
    analyze:
      config: Debug
    archive:
      config: Release
